# ce playbook permet de verifier si apache , nginx et tomcat sont installe dans les serveurs ou non
---
- name : checking services exist or not
  hosts: webservers
  gather_facts: yes
  
  tasks:
  - name: "Populate service facts"
    service_facts:
    
  - name: "See the service <httpd> facts as they are"
    debug:
      msg: "{{ansible_facts.services['httpd.service'].state}}"
    when:  ansible_facts.services['httpd.service'] is defined
    
  - name: "See the service <apache2> facts as they are"
    debug:
      msg: "{{ansible_facts.services['apache2.service'].state}}"
    when:  ansible_facts.services['apache2.service'] is defined
    
  - name: "See the service <nginx> facts as they are"
    debug:
      msg: "{{ansible_facts.services['nginx.service'].state}}"
    when:  ansible_facts.services['nginx.service'] is defined
   
  - name: "See the service <tomcat> facts as they are"
    debug:
      msg: "{{ansible_facts.services['tomcat.service'].state}}"
    when:  ansible_facts.services['tomcat.service'] is defined

