---
- name: Install nfs-common
  hosts: webservers
  gather_facts: yes
  become: yes

  tasks:
  - name: install nfs-common for Debian VM
    apt:
        name: nfs-common
        state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: install nfs-common for CentOS VM
    yum:
        name:  nfs-utils 
        state: present
    when: ansible_facts['os_family'] == "RedHat"
