---
- name: change_password_users
  hosts: webservers
  gather_facts: no
  become: yes

  tasks:
  - shell: getent passwd nour
    register: user_exists_nour
    ignore_errors: yes

  - name: change password for nour
    user:
      name: nour
      update_password: always 
      password: "{{ '409470' |password_hash('sha512') }}"
    when: user_exists_nour.rc == 0

