---
- name: deploy users
  hosts: webservers
  become: yes
  vars:
    x:  vault_users_password_nour
  tasks:
  - name: update password user1
    user:
      name: nour
      update_password: always
      password: "{{ x  |password_hash('sha512') }}"
      # no_log: true

