---
- name: deploy users
  hosts: webservers
  become: yes
  vars:
          simple_users:
          - { name: "nour", password: "{{ vault_users_password_nour }}" }
          - { name: "lina", password: "{{ vault_users_password_lina }}" }
  tasks:
  - name: update password
    user:
      name: "{{ item.name }}"
      update_password: always
      password: "{{ item.password |password_hash('sha512') }}" 
    with_items:
    - "{{ simple_users  }}"
      # no_log: true
      
       
