---
- name: change_password_users
  hosts: webservers
  gather_facts: no
  become: yes
  
  tasks:
    - name: change user1 password
      user:
        name: nour
        update_password: always
        password: "{{ '601523' |password_hash('sha512') }}"

